builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/ir2proxy/main.go
  flags:
  - -mod=readonly
  - -v
  goos:
  - windows
  - linux
  - darwin
  goarch:
  - amd64
release:
  github:
    owner: projectcontour
    name: ir2proxy
  prerelease: auto
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
brews:
- name: ir2proxy
  github:
    owner: projectcontour
    name: homebrew-ir2proxy
  homepage: "https://github.com/projectcontour/ir2proxy"
  description: "A tool to convert Contour's IngressRoute resources to HTTPProxy resources."
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
